export const GRAY_COLOR = '#BCBBBB'
export const WHITE_COLOR = '#F6F7FC'
export const BLUE_COLOR = '#98A4DF'
export const BLUE_HOVER_COLOR = '#747DAB'
export const BLACK_COLOR = '#212121'
export const PUBLICATION_COLOR = '#F1F3F9'
export const DETAILED_COLOR = '#7D7D7D'
